- hosts: localhost
  become: true
  tasks:
    - name: Task -1 Connect to GKE cluster
      shell: gcloud container clusters get-credentials gp-cluster --region europe-west1 --project iti-project-340821

    - name: Task -2 Deploying jenkins & loadbalancer servies
      command: kubectl apply -f Jenkins/
