apiVersion: v1
kind: Service
metadata:
  name: lb-servies
  labels:
    name:  lb-servies
    app: app-py
spec:
  type: LoadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  selector:
     app: app-py
     name: application-py